### ISSUE TITLE
Symfony 6 Support

### ISSUE THREAD

**Issue by colinodell** [okvpn/datadog-symfony#10]
I'd love to see support for Symfony 6 in this library :)

**Comment by michelv** [comment]
Seconded.

That support implies some upgrades in the require-dev section, as Symfony 6 requires PHP 8 and the PHPunit version that's used here is limited to PHP 7.

It may also imply dropping support for Symfony 4.4 or rewriting some of the tests, because some FrameworkBundle config options aren't available anymore starting from Symfony 5.3 (at least framework.session.storage_id has been replaced by .storage_factory_id).

**Comment by Chris53897** [comment]
I did a quick look and started a PR. There is more to change. Drop support for php 7 and symfony 4 will make a lot of things easier. I can say more after a closer look.

**Comment by vtsykun** [comment]
Fixed in #14
